"""add core database models

Revision ID: 698de01abfb7
Revises: 
Create Date: 2026-09-22 19:13:54.615304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '698de01abfb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attck_techniques',
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tactic', sa.String(length=50), nullable=True),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_technique_id'], ['attck_techniques.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attck_techniques', schema=None) as batch_op:
        batch_op.create_index('ix_attck_tactic_technique', ['tactic', 'technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attck_techniques_parent_technique_id'), ['parent_technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attck_techniques_tactic'), ['tactic'], unique=False)
        batch_op.create_index(batch_op.f('ix_attck_techniques_technique_id'), ['technique_id'], unique=True)

    op.create_table('detection_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index('ix_detection_rule_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_status'), ['status'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('telemetry_events',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_events_source'), ['source'], unique=False)
        batch_op.create_index('ix_telemetry_received_processed', ['received_at', 'processed'], unique=False)
        batch_op.create_index('ix_telemetry_source_type', ['source', 'event_type'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created_action', ['created_at', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_audit_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('ix_audit_user_action', ['user_id', 'action'], unique=False)

    op.create_table('detection_executions',
    sa.Column('detection_rule_id', sa.Integer(), nullable=False),
    sa.Column('telemetry_event_id', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['detection_rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telemetry_event_id'], ['telemetry_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detection_executions', schema=None) as batch_op:
        batch_op.create_index('ix_detection_execution_matched_created', ['matched', 'created_at'], unique=False)
        batch_op.create_index('ix_detection_execution_rule_event', ['detection_rule_id', 'telemetry_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_executions_detection_rule_id'), ['detection_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_executions_matched'), ['matched'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_executions_telemetry_event_id'), ['telemetry_event_id'], unique=False)

    op.create_table('incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incident_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('ix_incident_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_title'), ['title'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('alerts',
    sa.Column('detection_rule_id', sa.Integer(), nullable=False),
    sa.Column('detection_execution_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['detection_execution_id'], ['detection_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['detection_rule_id'], ['detection_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_assigned_status', ['assigned_to_id', 'status'], unique=False)
        batch_op.create_index('ix_alert_incident_status', ['incident_id', 'status'], unique=False)
        batch_op.create_index('ix_alert_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_detection_execution_id'), ['detection_execution_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_alerts_detection_rule_id'), ['detection_rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('alert_attck',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('attck_technique_id', sa.Integer(), nullable=False),
    sa.Column('mapped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attck_technique_id'], ['attck_techniques.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'attck_technique_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_attck')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_detection_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_detection_execution_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_assigned_to_id'))
        batch_op.drop_index('ix_alert_status_severity')
        batch_op.drop_index('ix_alert_incident_status')
        batch_op.drop_index('ix_alert_assigned_status')

    op.drop_table('alerts')
    op.drop_table('user_roles')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_title'))
        batch_op.drop_index(batch_op.f('ix_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_incidents_severity'))
        batch_op.drop_index(batch_op.f('ix_incidents_owner_id'))
        batch_op.drop_index('ix_incident_status_severity')
        batch_op.drop_index('ix_incident_owner_status')

    op.drop_table('incidents')
    with op.batch_alter_table('detection_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_executions_telemetry_event_id'))
        batch_op.drop_index(batch_op.f('ix_detection_executions_matched'))
        batch_op.drop_index(batch_op.f('ix_detection_executions_detection_rule_id'))
        batch_op.drop_index('ix_detection_execution_rule_event')
        batch_op.drop_index('ix_detection_execution_matched_created')

    op.drop_table('detection_executions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user_action')
        batch_op.drop_index('ix_audit_resource')
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_created_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetry_source_type')
        batch_op.drop_index('ix_telemetry_received_processed')
        batch_op.drop_index(batch_op.f('ix_telemetry_events_source'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_telemetry_events_event_type'))

    op.drop_table('telemetry_events')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_status'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_severity'))
        batch_op.drop_index(batch_op.f('ix_detection_rules_name'))
        batch_op.drop_index('ix_detection_rule_status_severity')

    op.drop_table('detection_rules')
    with op.batch_alter_table('attck_techniques', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attck_techniques_technique_id'))
        batch_op.drop_index(batch_op.f('ix_attck_techniques_tactic'))
        batch_op.drop_index(batch_op.f('ix_attck_techniques_parent_technique_id'))
        batch_op.drop_index('ix_attck_tactic_technique')

    op.drop_table('attck_techniques')
    # ### end Alembic commands ###
