"""add detection rule yaml fields

Revision ID: da7060530ddf
Revises: 698de01abfb7
Create Date: 2026-09-23 00:37:44.677511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'da7060530ddf'
down_revision = '698de01abfb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to detection_rules
    op.add_column('detection_rules', sa.Column('rule_id', sa.String(length=100), nullable=True))
    op.add_column('detection_rules', sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('detection_rules', sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('detection_rules', sa.Column('attck_techniques', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('detection_rules', sa.Column('test_cases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))

    # Remove the old status column and replace with enabled
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_rule_status_severity')
        batch_op.drop_index(batch_op.f('ix_detection_rules_status'))
        batch_op.drop_column('status')

    # Create new indexes
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index('ix_detection_rule_status_severity', ['enabled', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_rule_id'), ['rule_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detection_rules_rule_id'))
        batch_op.drop_index('ix_detection_rule_status_severity')

    # Add back status column and remove new columns
    op.add_column('detection_rules', sa.Column('status', sa.String(length=20), nullable=False, server_default='enabled'))

    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index('ix_detection_rule_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_status'), ['status'], unique=False)

    op.drop_column('detection_rules', 'test_cases')
    op.drop_column('detection_rules', 'attck_techniques')
    op.drop_column('detection_rules', 'tags')
    op.drop_column('detection_rules', 'enabled')
    op.drop_column('detection_rules', 'rule_id')

    with op.batch_alter_table('detection_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detection_rules_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_detection_rules_name'), ['name'], unique=False)
        batch_op.create_index('ix_detection_rule_status_severity', ['status', 'severity'], unique=False)

    # ### end Alembic commands ###